# Grafana provisioning. Prometheus datasources for the collector and the two
# consumers.
apiVersion: 1

datasources:
  - name: PudimNetMon
    uid: prom-collector
    type: prometheus
    access: proxy
    url: http://collector:8080
    isDefault: true
    editable: false

  - name: Storage Consumer
    uid: prom-storage
    type: prometheus
    access: proxy
    url: http://consumer-storage:9091
    editable: false
